// Code generated by protoc-gen-go. DO NOT EDIT.
// source: country.proto

package gservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Country struct {
	B                    *ResponseBase `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Countryname          string        `protobuf:"bytes,2,opt,name=countryname,proto3" json:"countryname,omitempty"`
	Isactive             bool          `protobuf:"varint,3,opt,name=isactive,proto3" json:"isactive,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Country) Reset()         { *m = Country{} }
func (m *Country) String() string { return proto.CompactTextString(m) }
func (*Country) ProtoMessage()    {}
func (*Country) Descriptor() ([]byte, []int) {
	return fileDescriptor_43a73f5bdb29770c, []int{0}
}

func (m *Country) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Country.Unmarshal(m, b)
}
func (m *Country) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Country.Marshal(b, m, deterministic)
}
func (m *Country) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Country.Merge(m, src)
}
func (m *Country) XXX_Size() int {
	return xxx_messageInfo_Country.Size(m)
}
func (m *Country) XXX_DiscardUnknown() {
	xxx_messageInfo_Country.DiscardUnknown(m)
}

var xxx_messageInfo_Country proto.InternalMessageInfo

func (m *Country) GetB() *ResponseBase {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *Country) GetCountryname() string {
	if m != nil {
		return m.Countryname
	}
	return ""
}

func (m *Country) GetIsactive() bool {
	if m != nil {
		return m.Isactive
	}
	return false
}

type City struct {
	B                    *ResponseBase `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Cityname             string        `protobuf:"bytes,2,opt,name=cityname,proto3" json:"cityname,omitempty"`
	Isactive             bool          `protobuf:"varint,3,opt,name=isactive,proto3" json:"isactive,omitempty"`
	Countryid            string        `protobuf:"bytes,4,opt,name=countryid,proto3" json:"countryid,omitempty"`
	Countryname          string        `protobuf:"bytes,5,opt,name=countryname,proto3" json:"countryname,omitempty"`
	Statename            string        `protobuf:"bytes,6,opt,name=statename,proto3" json:"statename,omitempty"`
	Stateid              string        `protobuf:"bytes,7,opt,name=stateid,proto3" json:"stateid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *City) Reset()         { *m = City{} }
func (m *City) String() string { return proto.CompactTextString(m) }
func (*City) ProtoMessage()    {}
func (*City) Descriptor() ([]byte, []int) {
	return fileDescriptor_43a73f5bdb29770c, []int{1}
}

func (m *City) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_City.Unmarshal(m, b)
}
func (m *City) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_City.Marshal(b, m, deterministic)
}
func (m *City) XXX_Merge(src proto.Message) {
	xxx_messageInfo_City.Merge(m, src)
}
func (m *City) XXX_Size() int {
	return xxx_messageInfo_City.Size(m)
}
func (m *City) XXX_DiscardUnknown() {
	xxx_messageInfo_City.DiscardUnknown(m)
}

var xxx_messageInfo_City proto.InternalMessageInfo

func (m *City) GetB() *ResponseBase {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *City) GetCityname() string {
	if m != nil {
		return m.Cityname
	}
	return ""
}

func (m *City) GetIsactive() bool {
	if m != nil {
		return m.Isactive
	}
	return false
}

func (m *City) GetCountryid() string {
	if m != nil {
		return m.Countryid
	}
	return ""
}

func (m *City) GetCountryname() string {
	if m != nil {
		return m.Countryname
	}
	return ""
}

func (m *City) GetStatename() string {
	if m != nil {
		return m.Statename
	}
	return ""
}

func (m *City) GetStateid() string {
	if m != nil {
		return m.Stateid
	}
	return ""
}

type State struct {
	B                    *ResponseBase `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Statename            string        `protobuf:"bytes,2,opt,name=statename,proto3" json:"statename,omitempty"`
	Isactive             bool          `protobuf:"varint,3,opt,name=isactive,proto3" json:"isactive,omitempty"`
	Countryid            string        `protobuf:"bytes,4,opt,name=countryid,proto3" json:"countryid,omitempty"`
	Countryname          string        `protobuf:"bytes,5,opt,name=countryname,proto3" json:"countryname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_43a73f5bdb29770c, []int{2}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetB() *ResponseBase {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *State) GetStatename() string {
	if m != nil {
		return m.Statename
	}
	return ""
}

func (m *State) GetIsactive() bool {
	if m != nil {
		return m.Isactive
	}
	return false
}

func (m *State) GetCountryid() string {
	if m != nil {
		return m.Countryid
	}
	return ""
}

func (m *State) GetCountryname() string {
	if m != nil {
		return m.Countryname
	}
	return ""
}

type StateList struct {
	States               []*State `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateList) Reset()         { *m = StateList{} }
func (m *StateList) String() string { return proto.CompactTextString(m) }
func (*StateList) ProtoMessage()    {}
func (*StateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_43a73f5bdb29770c, []int{3}
}

func (m *StateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateList.Unmarshal(m, b)
}
func (m *StateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateList.Marshal(b, m, deterministic)
}
func (m *StateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateList.Merge(m, src)
}
func (m *StateList) XXX_Size() int {
	return xxx_messageInfo_StateList.Size(m)
}
func (m *StateList) XXX_DiscardUnknown() {
	xxx_messageInfo_StateList.DiscardUnknown(m)
}

var xxx_messageInfo_StateList proto.InternalMessageInfo

func (m *StateList) GetStates() []*State {
	if m != nil {
		return m.States
	}
	return nil
}

type CityList struct {
	Cities               []*City  `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityList) Reset()         { *m = CityList{} }
func (m *CityList) String() string { return proto.CompactTextString(m) }
func (*CityList) ProtoMessage()    {}
func (*CityList) Descriptor() ([]byte, []int) {
	return fileDescriptor_43a73f5bdb29770c, []int{4}
}

func (m *CityList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityList.Unmarshal(m, b)
}
func (m *CityList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityList.Marshal(b, m, deterministic)
}
func (m *CityList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityList.Merge(m, src)
}
func (m *CityList) XXX_Size() int {
	return xxx_messageInfo_CityList.Size(m)
}
func (m *CityList) XXX_DiscardUnknown() {
	xxx_messageInfo_CityList.DiscardUnknown(m)
}

var xxx_messageInfo_CityList proto.InternalMessageInfo

func (m *CityList) GetCities() []*City {
	if m != nil {
		return m.Cities
	}
	return nil
}

type CountryList struct {
	Countries            []*Country `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CountryList) Reset()         { *m = CountryList{} }
func (m *CountryList) String() string { return proto.CompactTextString(m) }
func (*CountryList) ProtoMessage()    {}
func (*CountryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_43a73f5bdb29770c, []int{5}
}

func (m *CountryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountryList.Unmarshal(m, b)
}
func (m *CountryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountryList.Marshal(b, m, deterministic)
}
func (m *CountryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountryList.Merge(m, src)
}
func (m *CountryList) XXX_Size() int {
	return xxx_messageInfo_CountryList.Size(m)
}
func (m *CountryList) XXX_DiscardUnknown() {
	xxx_messageInfo_CountryList.DiscardUnknown(m)
}

var xxx_messageInfo_CountryList proto.InternalMessageInfo

func (m *CountryList) GetCountries() []*Country {
	if m != nil {
		return m.Countries
	}
	return nil
}

func init() {
	proto.RegisterType((*Country)(nil), "gservice.Country")
	proto.RegisterType((*City)(nil), "gservice.City")
	proto.RegisterType((*State)(nil), "gservice.State")
	proto.RegisterType((*StateList)(nil), "gservice.StateList")
	proto.RegisterType((*CityList)(nil), "gservice.CityList")
	proto.RegisterType((*CountryList)(nil), "gservice.CountryList")
}

func init() { proto.RegisterFile("country.proto", fileDescriptor_43a73f5bdb29770c) }

var fileDescriptor_43a73f5bdb29770c = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xcb, 0x4a, 0xf4, 0x40,
	0x10, 0x85, 0xe9, 0xb9, 0xe4, 0x52, 0xe1, 0xff, 0xc5, 0x5e, 0x48, 0x13, 0x66, 0x11, 0x1a, 0xd1,
	0xac, 0x22, 0x44, 0xd7, 0x2e, 0x9c, 0xad, 0xab, 0xf6, 0x09, 0x72, 0x69, 0xa4, 0x16, 0x49, 0x86,
	0x74, 0x3b, 0xe0, 0x13, 0xf9, 0x52, 0x3e, 0x8c, 0xa4, 0x72, 0x75, 0x04, 0x99, 0x8d, 0xbb, 0x54,
	0xd5, 0xf9, 0x72, 0xea, 0xd0, 0x05, 0xff, 0x8a, 0xe6, 0xad, 0xb6, 0xed, 0x7b, 0x72, 0x68, 0x1b,
	0xdb, 0x70, 0xef, 0xd5, 0xe8, 0xf6, 0x88, 0x85, 0x0e, 0x03, 0x5d, 0xe5, 0xba, 0xec, 0xdb, 0xb2,
	0x02, 0x77, 0xdf, 0xeb, 0xf8, 0x35, 0xb0, 0x5c, 0xb0, 0x88, 0xc5, 0x41, 0x7a, 0x95, 0x8c, 0xea,
	0x44, 0x69, 0x73, 0x68, 0x6a, 0xa3, 0x9f, 0x32, 0xa3, 0x15, 0xcb, 0x79, 0x04, 0xc1, 0xf0, 0xe3,
	0x3a, 0xab, 0xb4, 0x58, 0x45, 0x2c, 0xf6, 0xd5, 0xb2, 0xc5, 0x43, 0xf0, 0xd0, 0x64, 0x85, 0xc5,
	0xa3, 0x16, 0xeb, 0x88, 0xc5, 0x9e, 0x9a, 0x6a, 0xf9, 0xc9, 0x60, 0xb3, 0x47, 0x7b, 0xae, 0x59,
	0x08, 0x5e, 0x81, 0x76, 0xe9, 0x34, 0xd5, 0xbf, 0xd9, 0xf0, 0x1d, 0xf8, 0xc3, 0x46, 0x58, 0x8a,
	0x0d, 0x81, 0x73, 0xe3, 0x34, 0xc2, 0xf6, 0x67, 0x84, 0x1d, 0xf8, 0xc6, 0x66, 0x56, 0xd3, 0xdc,
	0xe9, 0xf9, 0xa9, 0xc1, 0x05, 0xb8, 0x54, 0x60, 0x29, 0x5c, 0x9a, 0x8d, 0xa5, 0xfc, 0x60, 0xb0,
	0x7d, 0xe9, 0xbe, 0xcf, 0xcc, 0xf7, 0xcd, 0x67, 0x75, 0xea, 0xf3, 0x87, 0x09, 0xe5, 0x03, 0xf8,
	0xb4, 0xe8, 0x33, 0x1a, 0xcb, 0x6f, 0xc1, 0x21, 0x57, 0x23, 0x58, 0xb4, 0x8e, 0x83, 0xf4, 0x62,
	0xde, 0x98, 0x44, 0x6a, 0x18, 0xcb, 0x14, 0xbc, 0xee, 0xf5, 0x08, 0xba, 0x01, 0xa7, 0x40, 0x8b,
	0x13, 0xf4, 0x7f, 0x86, 0x3a, 0x8d, 0x1a, 0xa6, 0xf2, 0x11, 0x82, 0xe1, 0xc2, 0x08, 0xbb, 0x1b,
	0x17, 0x9f, 0xc9, 0xcb, 0x05, 0xd9, 0x2b, 0xd5, 0xac, 0xc9, 0x1d, 0x3a, 0xd4, 0xfb, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x25, 0x05, 0x71, 0x5a, 0xd0, 0x02, 0x00, 0x00,
}
