// Code generated by protoc-gen-go. DO NOT EDIT.
// source: embed.proto

package gservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//embeded
type ResponseBase struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Createdby            string               `protobuf:"bytes,2,opt,name=createdby,proto3" json:"createdby,omitempty"`
	Createdat            string               `protobuf:"bytes,3,opt,name=createdat,proto3" json:"createdat,omitempty"`
	Updatedby            string               `protobuf:"bytes,4,opt,name=updatedby,proto3" json:"updatedby,omitempty"`
	Updatedat            string               `protobuf:"bytes,5,opt,name=updatedat,proto3" json:"updatedat,omitempty"`
	Createdatunix        *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdatunix,proto3" json:"createdatunix,omitempty"`
	Updatedatunix        *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updatedatunix,proto3" json:"updatedatunix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResponseBase) Reset()         { *m = ResponseBase{} }
func (m *ResponseBase) String() string { return proto.CompactTextString(m) }
func (*ResponseBase) ProtoMessage()    {}
func (*ResponseBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd263667ed585e61, []int{0}
}

func (m *ResponseBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseBase.Unmarshal(m, b)
}
func (m *ResponseBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseBase.Marshal(b, m, deterministic)
}
func (m *ResponseBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseBase.Merge(m, src)
}
func (m *ResponseBase) XXX_Size() int {
	return xxx_messageInfo_ResponseBase.Size(m)
}
func (m *ResponseBase) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseBase.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseBase proto.InternalMessageInfo

func (m *ResponseBase) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResponseBase) GetCreatedby() string {
	if m != nil {
		return m.Createdby
	}
	return ""
}

func (m *ResponseBase) GetCreatedat() string {
	if m != nil {
		return m.Createdat
	}
	return ""
}

func (m *ResponseBase) GetUpdatedby() string {
	if m != nil {
		return m.Updatedby
	}
	return ""
}

func (m *ResponseBase) GetUpdatedat() string {
	if m != nil {
		return m.Updatedat
	}
	return ""
}

func (m *ResponseBase) GetCreatedatunix() *timestamp.Timestamp {
	if m != nil {
		return m.Createdatunix
	}
	return nil
}

func (m *ResponseBase) GetUpdatedatunix() *timestamp.Timestamp {
	if m != nil {
		return m.Updatedatunix
	}
	return nil
}

type GeoLocation struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Radius               float64  `protobuf:"fixed64,3,opt,name=radius,proto3" json:"radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeoLocation) Reset()         { *m = GeoLocation{} }
func (m *GeoLocation) String() string { return proto.CompactTextString(m) }
func (*GeoLocation) ProtoMessage()    {}
func (*GeoLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd263667ed585e61, []int{1}
}

func (m *GeoLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoLocation.Unmarshal(m, b)
}
func (m *GeoLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoLocation.Marshal(b, m, deterministic)
}
func (m *GeoLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoLocation.Merge(m, src)
}
func (m *GeoLocation) XXX_Size() int {
	return xxx_messageInfo_GeoLocation.Size(m)
}
func (m *GeoLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoLocation.DiscardUnknown(m)
}

var xxx_messageInfo_GeoLocation proto.InternalMessageInfo

func (m *GeoLocation) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *GeoLocation) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *GeoLocation) GetRadius() float64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

type Locality struct {
	Countryid            string   `protobuf:"bytes,1,opt,name=countryid,proto3" json:"countryid,omitempty"`
	Countryname          string   `protobuf:"bytes,2,opt,name=countryname,proto3" json:"countryname,omitempty"`
	Stateid              string   `protobuf:"bytes,3,opt,name=stateid,proto3" json:"stateid,omitempty"`
	Statename            string   `protobuf:"bytes,4,opt,name=statename,proto3" json:"statename,omitempty"`
	Cityid               string   `protobuf:"bytes,5,opt,name=cityid,proto3" json:"cityid,omitempty"`
	Cityname             string   `protobuf:"bytes,6,opt,name=cityname,proto3" json:"cityname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Locality) Reset()         { *m = Locality{} }
func (m *Locality) String() string { return proto.CompactTextString(m) }
func (*Locality) ProtoMessage()    {}
func (*Locality) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd263667ed585e61, []int{2}
}

func (m *Locality) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Locality.Unmarshal(m, b)
}
func (m *Locality) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Locality.Marshal(b, m, deterministic)
}
func (m *Locality) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Locality.Merge(m, src)
}
func (m *Locality) XXX_Size() int {
	return xxx_messageInfo_Locality.Size(m)
}
func (m *Locality) XXX_DiscardUnknown() {
	xxx_messageInfo_Locality.DiscardUnknown(m)
}

var xxx_messageInfo_Locality proto.InternalMessageInfo

func (m *Locality) GetCountryid() string {
	if m != nil {
		return m.Countryid
	}
	return ""
}

func (m *Locality) GetCountryname() string {
	if m != nil {
		return m.Countryname
	}
	return ""
}

func (m *Locality) GetStateid() string {
	if m != nil {
		return m.Stateid
	}
	return ""
}

func (m *Locality) GetStatename() string {
	if m != nil {
		return m.Statename
	}
	return ""
}

func (m *Locality) GetCityid() string {
	if m != nil {
		return m.Cityid
	}
	return ""
}

func (m *Locality) GetCityname() string {
	if m != nil {
		return m.Cityname
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd263667ed585e61, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type FilterBase struct {
	Skip                 int32    `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Isactive             bool     `protobuf:"varint,3,opt,name=isactive,proto3" json:"isactive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterBase) Reset()         { *m = FilterBase{} }
func (m *FilterBase) String() string { return proto.CompactTextString(m) }
func (*FilterBase) ProtoMessage()    {}
func (*FilterBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd263667ed585e61, []int{4}
}

func (m *FilterBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterBase.Unmarshal(m, b)
}
func (m *FilterBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterBase.Marshal(b, m, deterministic)
}
func (m *FilterBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterBase.Merge(m, src)
}
func (m *FilterBase) XXX_Size() int {
	return xxx_messageInfo_FilterBase.Size(m)
}
func (m *FilterBase) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterBase.DiscardUnknown(m)
}

var xxx_messageInfo_FilterBase proto.InternalMessageInfo

func (m *FilterBase) GetSkip() int32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *FilterBase) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FilterBase) GetIsactive() bool {
	if m != nil {
		return m.Isactive
	}
	return false
}

func init() {
	proto.RegisterType((*ResponseBase)(nil), "gservice.ResponseBase")
	proto.RegisterType((*GeoLocation)(nil), "gservice.GeoLocation")
	proto.RegisterType((*Locality)(nil), "gservice.Locality")
	proto.RegisterType((*Empty)(nil), "gservice.Empty")
	proto.RegisterType((*FilterBase)(nil), "gservice.FilterBase")
}

func init() { proto.RegisterFile("embed.proto", fileDescriptor_bd263667ed585e61) }

var fileDescriptor_bd263667ed585e61 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xd1, 0xaa, 0x9b, 0x40,
	0x10, 0x45, 0x6f, 0x34, 0x66, 0x6c, 0x4b, 0x59, 0x4a, 0x91, 0x50, 0x68, 0xf0, 0x29, 0x4f, 0x06,
	0xda, 0x1f, 0x28, 0x85, 0xb6, 0x14, 0xfa, 0xb4, 0xf4, 0x07, 0x56, 0x9d, 0x86, 0xa1, 0xea, 0x8a,
	0x3b, 0x86, 0xe6, 0x57, 0xfa, 0x21, 0xfd, 0xbe, 0xb2, 0xa3, 0x31, 0xf1, 0xe9, 0xbe, 0xcd, 0x39,
	0xc7, 0x73, 0x9c, 0x39, 0x0a, 0x29, 0xb6, 0x25, 0xd6, 0x45, 0x3f, 0x58, 0xb6, 0x2a, 0x39, 0x3b,
	0x1c, 0x2e, 0x54, 0xe1, 0xfe, 0xfd, 0xd9, 0xda, 0x73, 0x83, 0x27, 0xe1, 0xcb, 0xf1, 0xd7, 0x89,
	0xa9, 0x45, 0xc7, 0xa6, 0xed, 0xa7, 0x47, 0xf3, 0xbf, 0x21, 0xbc, 0xd0, 0xe8, 0x7a, 0xdb, 0x39,
	0xfc, 0x6c, 0x1c, 0xaa, 0x57, 0x10, 0x52, 0x9d, 0x05, 0x87, 0xe0, 0xb8, 0xd3, 0x21, 0xd5, 0xea,
	0x1d, 0xec, 0xaa, 0x01, 0x0d, 0x63, 0x5d, 0x5e, 0xb3, 0x50, 0xe8, 0x3b, 0xf1, 0xa0, 0x1a, 0xce,
	0x9e, 0x56, 0xaa, 0x61, 0xaf, 0x8e, 0x7d, 0x3d, 0x7b, 0x37, 0x93, 0xba, 0x10, 0x0f, 0xaa, 0xe1,
	0x2c, 0x5a, 0xa9, 0x86, 0xd5, 0x27, 0x78, 0xb9, 0x04, 0x8d, 0x1d, 0xfd, 0xc9, 0xe2, 0x43, 0x70,
	0x4c, 0x3f, 0xec, 0x8b, 0xe9, 0xa2, 0xe2, 0x76, 0x51, 0xf1, 0xf3, 0x76, 0x91, 0x5e, 0x1b, 0x7c,
	0xc2, 0x12, 0x27, 0x09, 0xdb, 0xe7, 0x13, 0x56, 0x86, 0xfc, 0x3b, 0xa4, 0xdf, 0xd0, 0xfe, 0xb0,
	0x95, 0x61, 0xb2, 0x9d, 0x7a, 0x0d, 0x4f, 0x8d, 0x61, 0xe9, 0x26, 0xd0, 0x7e, 0x14, 0xc6, 0x76,
	0x52, 0x8b, 0x67, 0x6c, 0xa7, 0xde, 0x42, 0x3c, 0x98, 0x9a, 0x46, 0x27, 0x6d, 0x04, 0x7a, 0x46,
	0xf9, 0xbf, 0x00, 0x12, 0x1f, 0xd4, 0x10, 0x4f, 0xad, 0xd9, 0xb1, 0xe3, 0xe1, 0xba, 0x54, 0x7d,
	0x27, 0xd4, 0x01, 0xd2, 0x19, 0x74, 0xa6, 0xc5, 0xb9, 0xf3, 0x47, 0x4a, 0x65, 0xb0, 0x75, 0x6c,
	0x18, 0xa9, 0x9e, 0x3b, 0xbf, 0x41, 0x9f, 0x2c, 0xa3, 0x38, 0xe7, 0xc6, 0x17, 0xc2, 0x2f, 0x57,
	0x11, 0xfb, 0x97, 0x4e, 0x75, 0xcf, 0x48, 0xed, 0x21, 0xf1, 0x93, 0x98, 0x62, 0x51, 0x16, 0x9c,
	0x6f, 0x21, 0xfa, 0xd2, 0xf6, 0x7c, 0xcd, 0x35, 0xc0, 0x57, 0x6a, 0x18, 0x07, 0xf9, 0x4d, 0x14,
	0x6c, 0xdc, 0x6f, 0xea, 0x65, 0xfb, 0x48, 0xcb, 0xac, 0xde, 0x40, 0xd4, 0x50, 0x4b, 0x2c, 0x2b,
	0x47, 0x7a, 0x02, 0x3e, 0x9c, 0x9c, 0xa9, 0x98, 0x2e, 0x28, 0xdb, 0x26, 0x7a, 0xc1, 0x65, 0x2c,
	0xdf, 0xe0, 0xe3, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x49, 0x1b, 0xb9, 0xbe, 0xbe, 0x02, 0x00,
	0x00,
}
