// Code generated by protoc-gen-go. DO NOT EDIT.
// source: requests.proto

package gservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FilterLocation struct {
	Countryid            string   `protobuf:"bytes,1,opt,name=countryid,proto3" json:"countryid,omitempty"`
	Stateid              string   `protobuf:"bytes,2,opt,name=stateid,proto3" json:"stateid,omitempty"`
	Cityid               string   `protobuf:"bytes,3,opt,name=cityid,proto3" json:"cityid,omitempty"`
	Isactive             bool     `protobuf:"varint,4,opt,name=isactive,proto3" json:"isactive,omitempty"`
	Countryname          string   `protobuf:"bytes,6,opt,name=countryname,proto3" json:"countryname,omitempty"`
	Statename            string   `protobuf:"bytes,7,opt,name=statename,proto3" json:"statename,omitempty"`
	Cityname             string   `protobuf:"bytes,8,opt,name=cityname,proto3" json:"cityname,omitempty"`
	Locationname         string   `protobuf:"bytes,9,opt,name=locationname,proto3" json:"locationname,omitempty"`
	Locationid           string   `protobuf:"bytes,10,opt,name=locationid,proto3" json:"locationid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterLocation) Reset()         { *m = FilterLocation{} }
func (m *FilterLocation) String() string { return proto.CompactTextString(m) }
func (*FilterLocation) ProtoMessage()    {}
func (*FilterLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{0}
}

func (m *FilterLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterLocation.Unmarshal(m, b)
}
func (m *FilterLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterLocation.Marshal(b, m, deterministic)
}
func (m *FilterLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterLocation.Merge(m, src)
}
func (m *FilterLocation) XXX_Size() int {
	return xxx_messageInfo_FilterLocation.Size(m)
}
func (m *FilterLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterLocation.DiscardUnknown(m)
}

var xxx_messageInfo_FilterLocation proto.InternalMessageInfo

func (m *FilterLocation) GetCountryid() string {
	if m != nil {
		return m.Countryid
	}
	return ""
}

func (m *FilterLocation) GetStateid() string {
	if m != nil {
		return m.Stateid
	}
	return ""
}

func (m *FilterLocation) GetCityid() string {
	if m != nil {
		return m.Cityid
	}
	return ""
}

func (m *FilterLocation) GetIsactive() bool {
	if m != nil {
		return m.Isactive
	}
	return false
}

func (m *FilterLocation) GetCountryname() string {
	if m != nil {
		return m.Countryname
	}
	return ""
}

func (m *FilterLocation) GetStatename() string {
	if m != nil {
		return m.Statename
	}
	return ""
}

func (m *FilterLocation) GetCityname() string {
	if m != nil {
		return m.Cityname
	}
	return ""
}

func (m *FilterLocation) GetLocationname() string {
	if m != nil {
		return m.Locationname
	}
	return ""
}

func (m *FilterLocation) GetLocationid() string {
	if m != nil {
		return m.Locationid
	}
	return ""
}

type FilterCategory struct {
	Categoryid string `protobuf:"bytes,1,opt,name=categoryid,proto3" json:"categoryid,omitempty"`
	// Types that are valid to be assigned to Isactive:
	//	*FilterCategory_HasIsactive
	//	*FilterCategory_IsactiveValue
	Isactive             isFilterCategory_Isactive `protobuf_oneof:"isactive"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *FilterCategory) Reset()         { *m = FilterCategory{} }
func (m *FilterCategory) String() string { return proto.CompactTextString(m) }
func (*FilterCategory) ProtoMessage()    {}
func (*FilterCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{1}
}

func (m *FilterCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterCategory.Unmarshal(m, b)
}
func (m *FilterCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterCategory.Marshal(b, m, deterministic)
}
func (m *FilterCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterCategory.Merge(m, src)
}
func (m *FilterCategory) XXX_Size() int {
	return xxx_messageInfo_FilterCategory.Size(m)
}
func (m *FilterCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterCategory.DiscardUnknown(m)
}

var xxx_messageInfo_FilterCategory proto.InternalMessageInfo

func (m *FilterCategory) GetCategoryid() string {
	if m != nil {
		return m.Categoryid
	}
	return ""
}

type isFilterCategory_Isactive interface {
	isFilterCategory_Isactive()
}

type FilterCategory_HasIsactive struct {
	HasIsactive bool `protobuf:"varint,2,opt,name=has_isactive,json=hasIsactive,proto3,oneof"`
}

type FilterCategory_IsactiveValue struct {
	IsactiveValue bool `protobuf:"varint,3,opt,name=isactive_value,json=isactiveValue,proto3,oneof"`
}

func (*FilterCategory_HasIsactive) isFilterCategory_Isactive() {}

func (*FilterCategory_IsactiveValue) isFilterCategory_Isactive() {}

func (m *FilterCategory) GetIsactive() isFilterCategory_Isactive {
	if m != nil {
		return m.Isactive
	}
	return nil
}

func (m *FilterCategory) GetHasIsactive() bool {
	if x, ok := m.GetIsactive().(*FilterCategory_HasIsactive); ok {
		return x.HasIsactive
	}
	return false
}

func (m *FilterCategory) GetIsactiveValue() bool {
	if x, ok := m.GetIsactive().(*FilterCategory_IsactiveValue); ok {
		return x.IsactiveValue
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FilterCategory) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FilterCategory_HasIsactive)(nil),
		(*FilterCategory_IsactiveValue)(nil),
	}
}

type FilterCategoryDetail struct {
	Categoryid       string `protobuf:"bytes,1,opt,name=categoryid,proto3" json:"categoryid,omitempty"`
	Categorydetailid string `protobuf:"bytes,2,opt,name=categorydetailid,proto3" json:"categorydetailid,omitempty"`
	// Types that are valid to be assigned to Isactive:
	//	*FilterCategoryDetail_HasIsactive
	//	*FilterCategoryDetail_IsactiveValue
	Isactive             isFilterCategoryDetail_Isactive `protobuf_oneof:"isactive"`
	Parentcategoryid     string                          `protobuf:"bytes,5,opt,name=parentcategoryid,proto3" json:"parentcategoryid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *FilterCategoryDetail) Reset()         { *m = FilterCategoryDetail{} }
func (m *FilterCategoryDetail) String() string { return proto.CompactTextString(m) }
func (*FilterCategoryDetail) ProtoMessage()    {}
func (*FilterCategoryDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{2}
}

func (m *FilterCategoryDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterCategoryDetail.Unmarshal(m, b)
}
func (m *FilterCategoryDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterCategoryDetail.Marshal(b, m, deterministic)
}
func (m *FilterCategoryDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterCategoryDetail.Merge(m, src)
}
func (m *FilterCategoryDetail) XXX_Size() int {
	return xxx_messageInfo_FilterCategoryDetail.Size(m)
}
func (m *FilterCategoryDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterCategoryDetail.DiscardUnknown(m)
}

var xxx_messageInfo_FilterCategoryDetail proto.InternalMessageInfo

func (m *FilterCategoryDetail) GetCategoryid() string {
	if m != nil {
		return m.Categoryid
	}
	return ""
}

func (m *FilterCategoryDetail) GetCategorydetailid() string {
	if m != nil {
		return m.Categorydetailid
	}
	return ""
}

type isFilterCategoryDetail_Isactive interface {
	isFilterCategoryDetail_Isactive()
}

type FilterCategoryDetail_HasIsactive struct {
	HasIsactive bool `protobuf:"varint,3,opt,name=has_isactive,json=hasIsactive,proto3,oneof"`
}

type FilterCategoryDetail_IsactiveValue struct {
	IsactiveValue bool `protobuf:"varint,4,opt,name=isactive_value,json=isactiveValue,proto3,oneof"`
}

func (*FilterCategoryDetail_HasIsactive) isFilterCategoryDetail_Isactive() {}

func (*FilterCategoryDetail_IsactiveValue) isFilterCategoryDetail_Isactive() {}

func (m *FilterCategoryDetail) GetIsactive() isFilterCategoryDetail_Isactive {
	if m != nil {
		return m.Isactive
	}
	return nil
}

func (m *FilterCategoryDetail) GetHasIsactive() bool {
	if x, ok := m.GetIsactive().(*FilterCategoryDetail_HasIsactive); ok {
		return x.HasIsactive
	}
	return false
}

func (m *FilterCategoryDetail) GetIsactiveValue() bool {
	if x, ok := m.GetIsactive().(*FilterCategoryDetail_IsactiveValue); ok {
		return x.IsactiveValue
	}
	return false
}

func (m *FilterCategoryDetail) GetParentcategoryid() string {
	if m != nil {
		return m.Parentcategoryid
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FilterCategoryDetail) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FilterCategoryDetail_HasIsactive)(nil),
		(*FilterCategoryDetail_IsactiveValue)(nil),
	}
}

type FilterFeature struct {
	Featureid        string `protobuf:"bytes,1,opt,name=featureid,proto3" json:"featureid,omitempty"`
	Categorydetailid string `protobuf:"bytes,2,opt,name=categorydetailid,proto3" json:"categorydetailid,omitempty"`
	Name             string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Locationid       string `protobuf:"bytes,4,opt,name=locationid,proto3" json:"locationid,omitempty"`
	Isaddon          bool   `protobuf:"varint,5,opt,name=isaddon,proto3" json:"isaddon,omitempty"`
	// Types that are valid to be assigned to Isactive:
	//	*FilterFeature_HasIsactive
	//	*FilterFeature_IsactiveValue
	Isactive             isFilterFeature_Isactive `protobuf_oneof:"isactive"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *FilterFeature) Reset()         { *m = FilterFeature{} }
func (m *FilterFeature) String() string { return proto.CompactTextString(m) }
func (*FilterFeature) ProtoMessage()    {}
func (*FilterFeature) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{3}
}

func (m *FilterFeature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterFeature.Unmarshal(m, b)
}
func (m *FilterFeature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterFeature.Marshal(b, m, deterministic)
}
func (m *FilterFeature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterFeature.Merge(m, src)
}
func (m *FilterFeature) XXX_Size() int {
	return xxx_messageInfo_FilterFeature.Size(m)
}
func (m *FilterFeature) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterFeature.DiscardUnknown(m)
}

var xxx_messageInfo_FilterFeature proto.InternalMessageInfo

func (m *FilterFeature) GetFeatureid() string {
	if m != nil {
		return m.Featureid
	}
	return ""
}

func (m *FilterFeature) GetCategorydetailid() string {
	if m != nil {
		return m.Categorydetailid
	}
	return ""
}

func (m *FilterFeature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FilterFeature) GetLocationid() string {
	if m != nil {
		return m.Locationid
	}
	return ""
}

func (m *FilterFeature) GetIsaddon() bool {
	if m != nil {
		return m.Isaddon
	}
	return false
}

type isFilterFeature_Isactive interface {
	isFilterFeature_Isactive()
}

type FilterFeature_HasIsactive struct {
	HasIsactive bool `protobuf:"varint,6,opt,name=has_isactive,json=hasIsactive,proto3,oneof"`
}

type FilterFeature_IsactiveValue struct {
	IsactiveValue bool `protobuf:"varint,7,opt,name=isactive_value,json=isactiveValue,proto3,oneof"`
}

func (*FilterFeature_HasIsactive) isFilterFeature_Isactive() {}

func (*FilterFeature_IsactiveValue) isFilterFeature_Isactive() {}

func (m *FilterFeature) GetIsactive() isFilterFeature_Isactive {
	if m != nil {
		return m.Isactive
	}
	return nil
}

func (m *FilterFeature) GetHasIsactive() bool {
	if x, ok := m.GetIsactive().(*FilterFeature_HasIsactive); ok {
		return x.HasIsactive
	}
	return false
}

func (m *FilterFeature) GetIsactiveValue() bool {
	if x, ok := m.GetIsactive().(*FilterFeature_IsactiveValue); ok {
		return x.IsactiveValue
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FilterFeature) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FilterFeature_HasIsactive)(nil),
		(*FilterFeature_IsactiveValue)(nil),
	}
}

type FilterStaff struct {
	Userid        string `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Locationid    string `protobuf:"bytes,2,opt,name=locationid,proto3" json:"locationid,omitempty"`
	Firstname     string `protobuf:"bytes,3,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string `protobuf:"bytes,4,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email         string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Designation   string `protobuf:"bytes,6,opt,name=designation,proto3" json:"designation,omitempty"`
	Issecondshift string `protobuf:"bytes,7,opt,name=issecondshift,proto3" json:"issecondshift,omitempty"`
	// Types that are valid to be assigned to Isactive:
	//	*FilterStaff_HasIsactive
	//	*FilterStaff_IsactiveValue
	Isactive             isFilterStaff_Isactive `protobuf_oneof:"isactive"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *FilterStaff) Reset()         { *m = FilterStaff{} }
func (m *FilterStaff) String() string { return proto.CompactTextString(m) }
func (*FilterStaff) ProtoMessage()    {}
func (*FilterStaff) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{4}
}

func (m *FilterStaff) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterStaff.Unmarshal(m, b)
}
func (m *FilterStaff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterStaff.Marshal(b, m, deterministic)
}
func (m *FilterStaff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterStaff.Merge(m, src)
}
func (m *FilterStaff) XXX_Size() int {
	return xxx_messageInfo_FilterStaff.Size(m)
}
func (m *FilterStaff) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterStaff.DiscardUnknown(m)
}

var xxx_messageInfo_FilterStaff proto.InternalMessageInfo

func (m *FilterStaff) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *FilterStaff) GetLocationid() string {
	if m != nil {
		return m.Locationid
	}
	return ""
}

func (m *FilterStaff) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *FilterStaff) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *FilterStaff) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *FilterStaff) GetDesignation() string {
	if m != nil {
		return m.Designation
	}
	return ""
}

func (m *FilterStaff) GetIssecondshift() string {
	if m != nil {
		return m.Issecondshift
	}
	return ""
}

type isFilterStaff_Isactive interface {
	isFilterStaff_Isactive()
}

type FilterStaff_HasIsactive struct {
	HasIsactive bool `protobuf:"varint,8,opt,name=has_isactive,json=hasIsactive,proto3,oneof"`
}

type FilterStaff_IsactiveValue struct {
	IsactiveValue bool `protobuf:"varint,9,opt,name=isactive_value,json=isactiveValue,proto3,oneof"`
}

func (*FilterStaff_HasIsactive) isFilterStaff_Isactive() {}

func (*FilterStaff_IsactiveValue) isFilterStaff_Isactive() {}

func (m *FilterStaff) GetIsactive() isFilterStaff_Isactive {
	if m != nil {
		return m.Isactive
	}
	return nil
}

func (m *FilterStaff) GetHasIsactive() bool {
	if x, ok := m.GetIsactive().(*FilterStaff_HasIsactive); ok {
		return x.HasIsactive
	}
	return false
}

func (m *FilterStaff) GetIsactiveValue() bool {
	if x, ok := m.GetIsactive().(*FilterStaff_IsactiveValue); ok {
		return x.IsactiveValue
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FilterStaff) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FilterStaff_HasIsactive)(nil),
		(*FilterStaff_IsactiveValue)(nil),
	}
}

func init() {
	proto.RegisterType((*FilterLocation)(nil), "gservice.FilterLocation")
	proto.RegisterType((*FilterCategory)(nil), "gservice.FilterCategory")
	proto.RegisterType((*FilterCategoryDetail)(nil), "gservice.FilterCategoryDetail")
	proto.RegisterType((*FilterFeature)(nil), "gservice.FilterFeature")
	proto.RegisterType((*FilterStaff)(nil), "gservice.FilterStaff")
}

func init() { proto.RegisterFile("requests.proto", fileDescriptor_9c9ccec99da7c9b4) }

var fileDescriptor_9c9ccec99da7c9b4 = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x35, 0xd9, 0x6c, 0x9b, 0xde, 0x6e, 0x8b, 0x0c, 0x8b, 0x04, 0x11, 0x29, 0x55, 0x70, 0xf1,
	0xc1, 0x17, 0xff, 0x40, 0x65, 0x51, 0xf0, 0xa9, 0x82, 0xaf, 0xcb, 0x98, 0xdc, 0xb6, 0x03, 0xd9,
	0x64, 0x9d, 0xb9, 0x29, 0xec, 0xa3, 0xaf, 0x7e, 0x83, 0xff, 0xe1, 0x2f, 0xf9, 0x19, 0x32, 0x37,
	0x33, 0xd3, 0xa4, 0x59, 0x68, 0xf7, 0xad, 0xe7, 0xdc, 0x99, 0xdc, 0x73, 0xce, 0xdc, 0x5b, 0x98,
	0x6b, 0xfc, 0xd9, 0xa0, 0x21, 0xf3, 0xee, 0x4e, 0xd7, 0x54, 0x8b, 0x74, 0x63, 0x50, 0xef, 0x54,
	0x8e, 0xcb, 0x3f, 0x31, 0xcc, 0xaf, 0x55, 0x49, 0xa8, 0xbf, 0xd6, 0xb9, 0x24, 0x55, 0x57, 0xe2,
	0x05, 0x4c, 0xf2, 0xba, 0xa9, 0x48, 0xdf, 0xab, 0x22, 0x8b, 0x16, 0xd1, 0xd5, 0x64, 0xb5, 0x27,
	0x44, 0x06, 0x63, 0x43, 0x92, 0x50, 0x15, 0x59, 0xcc, 0x35, 0x0f, 0xc5, 0x33, 0x18, 0xe5, 0x8a,
	0xec, 0xa5, 0x33, 0x2e, 0x38, 0x24, 0x9e, 0x43, 0xaa, 0x8c, 0xcc, 0x49, 0xed, 0x30, 0x4b, 0x16,
	0xd1, 0x55, 0xba, 0x0a, 0x58, 0x2c, 0x60, 0xea, 0x3e, 0x5d, 0xc9, 0x5b, 0xcc, 0x46, 0x7c, 0xb1,
	0x4b, 0x59, 0x35, 0xdc, 0x80, 0xeb, 0xe3, 0x56, 0x4d, 0x20, 0xec, 0xb7, 0x6d, 0x17, 0x2e, 0xa6,
	0x5c, 0x0c, 0x58, 0x2c, 0xe1, 0xa2, 0x74, 0x9e, 0xb8, 0x3e, 0xe1, 0x7a, 0x8f, 0x13, 0x2f, 0x01,
	0x3c, 0x56, 0x45, 0x06, 0x7c, 0xa2, 0xc3, 0x2c, 0x7f, 0x47, 0x3e, 0x9e, 0x8f, 0x92, 0x70, 0x53,
	0xeb, 0x7b, 0x7b, 0x25, 0x77, 0xbf, 0x43, 0x3e, 0x1d, 0x46, 0xbc, 0x82, 0x8b, 0xad, 0x34, 0x37,
	0xc1, 0xb2, 0x4d, 0x29, 0xfd, 0xfc, 0x64, 0x35, 0xdd, 0x4a, 0xf3, 0xc5, 0xfb, 0x7e, 0x03, 0x73,
	0x7f, 0xe0, 0x66, 0x27, 0xcb, 0x06, 0x39, 0x33, 0x7b, 0x6c, 0xe6, 0xf9, 0xef, 0x96, 0xfe, 0x00,
	0xfb, 0xf0, 0x96, 0xff, 0x22, 0xb8, 0xec, 0x8b, 0xf9, 0x84, 0x24, 0x55, 0x79, 0x54, 0xd2, 0x5b,
	0x78, 0xea, 0x51, 0xc1, 0x37, 0xc2, 0xe3, 0x0d, 0xf8, 0x81, 0xfc, 0xb3, 0xd3, 0xe4, 0x27, 0x0f,
	0xca, 0xb7, 0x9d, 0xef, 0xa4, 0xc6, 0x8a, 0x3a, 0xfa, 0xce, 0xdb, 0xce, 0x87, 0x7c, 0xcf, 0xea,
	0xaf, 0x18, 0x66, 0xad, 0xd5, 0x6b, 0x94, 0xd4, 0x68, 0x9e, 0x83, 0x75, 0xfb, 0x73, 0x3f, 0x95,
	0x81, 0x78, 0x94, 0x43, 0x01, 0x09, 0xcf, 0x43, 0x3b, 0xa5, 0xc9, 0x03, 0x73, 0x90, 0x1c, 0xce,
	0x81, 0x9d, 0x7a, 0x65, 0x64, 0x51, 0xd4, 0x15, 0xcb, 0x4f, 0x57, 0x1e, 0x0e, 0xf2, 0x1a, 0x9d,
	0x96, 0xd7, 0xf8, 0xf8, 0x73, 0xff, 0x8d, 0x61, 0xda, 0x66, 0xf0, 0x8d, 0xe4, 0x7a, 0x6d, 0xf7,
	0xab, 0x31, 0xa8, 0x83, 0x7d, 0x87, 0x0e, 0xb4, 0xc7, 0x03, 0xed, 0x36, 0x39, 0xa5, 0x0d, 0x75,
	0x4c, 0xef, 0x09, 0xbb, 0x41, 0xa5, 0x74, 0xc5, 0xd6, 0x77, 0xc0, 0xe2, 0x12, 0xce, 0xf1, 0x56,
	0xaa, 0xd2, 0x3d, 0x59, 0x0b, 0xec, 0xce, 0x16, 0x68, 0xd4, 0xa6, 0xe2, 0x06, 0x7e, 0x67, 0x3b,
	0x94, 0x78, 0x0d, 0x33, 0x65, 0x0c, 0xe6, 0x75, 0x55, 0x98, 0xad, 0x5a, 0x93, 0xdb, 0xdb, 0x3e,
	0x39, 0x48, 0x2e, 0x3d, 0x2d, 0xb9, 0xc9, 0xd1, 0xe4, 0x7e, 0x8c, 0xf8, 0x5f, 0xee, 0xfd, 0xff,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x33, 0xef, 0x27, 0xf7, 0x04, 0x00, 0x00,
}
