// Code generated by protoc-gen-go. DO NOT EDIT.
// source: responses.proto

package gservice

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MeraResponse struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeraResponse) Reset()         { *m = MeraResponse{} }
func (m *MeraResponse) String() string { return proto.CompactTextString(m) }
func (*MeraResponse) ProtoMessage()    {}
func (*MeraResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8192a35440e287, []int{0}
}

func (m *MeraResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeraResponse.Unmarshal(m, b)
}
func (m *MeraResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeraResponse.Marshal(b, m, deterministic)
}
func (m *MeraResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeraResponse.Merge(m, src)
}
func (m *MeraResponse) XXX_Size() int {
	return xxx_messageInfo_MeraResponse.Size(m)
}
func (m *MeraResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MeraResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MeraResponse proto.InternalMessageInfo

func (m *MeraResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type Location struct {
	B                    *ResponseBase `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Displayname          string        `protobuf:"bytes,3,opt,name=displayname,proto3" json:"displayname,omitempty"`
	Isactive             bool          `protobuf:"varint,4,opt,name=isactive,proto3" json:"isactive,omitempty"`
	Gloc                 *GeoLocation  `protobuf:"bytes,5,opt,name=gloc,proto3" json:"gloc,omitempty"`
	Locality             *Locality     `protobuf:"bytes,6,opt,name=locality,proto3" json:"locality,omitempty"`
	Addressline1         string        `protobuf:"bytes,7,opt,name=addressline1,proto3" json:"addressline1,omitempty"`
	Addressline2         string        `protobuf:"bytes,8,opt,name=addressline2,proto3" json:"addressline2,omitempty"`
	Mobile               string        `protobuf:"bytes,9,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Phonenumber          string        `protobuf:"bytes,10,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Fax                  string        `protobuf:"bytes,11,opt,name=fax,proto3" json:"fax,omitempty"`
	Allfeatures          *FeatureList  `protobuf:"bytes,12,opt,name=allfeatures,proto3" json:"allfeatures,omitempty"`
	Locationfeatures     *FeatureList  `protobuf:"bytes,13,opt,name=locationfeatures,proto3" json:"locationfeatures,omitempty"`
	Locationfeatureids   []string      `protobuf:"bytes,14,rep,name=locationfeatureids,proto3" json:"locationfeatureids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8192a35440e287, []int{1}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetB() *ResponseBase {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *Location) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Location) GetDisplayname() string {
	if m != nil {
		return m.Displayname
	}
	return ""
}

func (m *Location) GetIsactive() bool {
	if m != nil {
		return m.Isactive
	}
	return false
}

func (m *Location) GetGloc() *GeoLocation {
	if m != nil {
		return m.Gloc
	}
	return nil
}

func (m *Location) GetLocality() *Locality {
	if m != nil {
		return m.Locality
	}
	return nil
}

func (m *Location) GetAddressline1() string {
	if m != nil {
		return m.Addressline1
	}
	return ""
}

func (m *Location) GetAddressline2() string {
	if m != nil {
		return m.Addressline2
	}
	return ""
}

func (m *Location) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Location) GetPhonenumber() string {
	if m != nil {
		return m.Phonenumber
	}
	return ""
}

func (m *Location) GetFax() string {
	if m != nil {
		return m.Fax
	}
	return ""
}

func (m *Location) GetAllfeatures() *FeatureList {
	if m != nil {
		return m.Allfeatures
	}
	return nil
}

func (m *Location) GetLocationfeatures() *FeatureList {
	if m != nil {
		return m.Locationfeatures
	}
	return nil
}

func (m *Location) GetLocationfeatureids() []string {
	if m != nil {
		return m.Locationfeatureids
	}
	return nil
}

type LocationList struct {
	Locations            []*Location `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LocationList) Reset()         { *m = LocationList{} }
func (m *LocationList) String() string { return proto.CompactTextString(m) }
func (*LocationList) ProtoMessage()    {}
func (*LocationList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8192a35440e287, []int{2}
}

func (m *LocationList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationList.Unmarshal(m, b)
}
func (m *LocationList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationList.Marshal(b, m, deterministic)
}
func (m *LocationList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationList.Merge(m, src)
}
func (m *LocationList) XXX_Size() int {
	return xxx_messageInfo_LocationList.Size(m)
}
func (m *LocationList) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationList.DiscardUnknown(m)
}

var xxx_messageInfo_LocationList proto.InternalMessageInfo

func (m *LocationList) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

type Category struct {
	B                    *ResponseBase `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Isactive             bool          `protobuf:"varint,3,opt,name=isactive,proto3" json:"isactive,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8192a35440e287, []int{3}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetB() *ResponseBase {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetIsactive() bool {
	if m != nil {
		return m.Isactive
	}
	return false
}

type CategoryDetail struct {
	B                    *ResponseBase `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Isactive             bool          `protobuf:"varint,3,opt,name=isactive,proto3" json:"isactive,omitempty"`
	Categoryid           string        `protobuf:"bytes,4,opt,name=categoryid,proto3" json:"categoryid,omitempty"`
	Categoryname         string        `protobuf:"bytes,5,opt,name=categoryname,proto3" json:"categoryname,omitempty"`
	Parentcategoryid     string        `protobuf:"bytes,6,opt,name=parentcategoryid,proto3" json:"parentcategoryid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CategoryDetail) Reset()         { *m = CategoryDetail{} }
func (m *CategoryDetail) String() string { return proto.CompactTextString(m) }
func (*CategoryDetail) ProtoMessage()    {}
func (*CategoryDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8192a35440e287, []int{4}
}

func (m *CategoryDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryDetail.Unmarshal(m, b)
}
func (m *CategoryDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryDetail.Marshal(b, m, deterministic)
}
func (m *CategoryDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryDetail.Merge(m, src)
}
func (m *CategoryDetail) XXX_Size() int {
	return xxx_messageInfo_CategoryDetail.Size(m)
}
func (m *CategoryDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryDetail.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryDetail proto.InternalMessageInfo

func (m *CategoryDetail) GetB() *ResponseBase {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *CategoryDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CategoryDetail) GetIsactive() bool {
	if m != nil {
		return m.Isactive
	}
	return false
}

func (m *CategoryDetail) GetCategoryid() string {
	if m != nil {
		return m.Categoryid
	}
	return ""
}

func (m *CategoryDetail) GetCategoryname() string {
	if m != nil {
		return m.Categoryname
	}
	return ""
}

func (m *CategoryDetail) GetParentcategoryid() string {
	if m != nil {
		return m.Parentcategoryid
	}
	return ""
}

type Feature struct {
	B                    *ResponseBase `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Isactive             bool          `protobuf:"varint,3,opt,name=isactive,proto3" json:"isactive,omitempty"`
	Locationid           string        `protobuf:"bytes,4,opt,name=locationid,proto3" json:"locationid,omitempty"`
	Locationname         string        `protobuf:"bytes,5,opt,name=locationname,proto3" json:"locationname,omitempty"`
	Categorydetailid     string        `protobuf:"bytes,6,opt,name=categorydetailid,proto3" json:"categorydetailid,omitempty"`
	Categorydetailname   string        `protobuf:"bytes,7,opt,name=categorydetailname,proto3" json:"categorydetailname,omitempty"`
	Currncy              string        `protobuf:"bytes,8,opt,name=currncy,proto3" json:"currncy,omitempty"`
	Price                float64       `protobuf:"fixed64,9,opt,name=price,proto3" json:"price,omitempty"`
	Isaddon              bool          `protobuf:"varint,10,opt,name=isaddon,proto3" json:"isaddon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8192a35440e287, []int{5}
}

func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (m *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(m, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetB() *ResponseBase {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *Feature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feature) GetIsactive() bool {
	if m != nil {
		return m.Isactive
	}
	return false
}

func (m *Feature) GetLocationid() string {
	if m != nil {
		return m.Locationid
	}
	return ""
}

func (m *Feature) GetLocationname() string {
	if m != nil {
		return m.Locationname
	}
	return ""
}

func (m *Feature) GetCategorydetailid() string {
	if m != nil {
		return m.Categorydetailid
	}
	return ""
}

func (m *Feature) GetCategorydetailname() string {
	if m != nil {
		return m.Categorydetailname
	}
	return ""
}

func (m *Feature) GetCurrncy() string {
	if m != nil {
		return m.Currncy
	}
	return ""
}

func (m *Feature) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Feature) GetIsaddon() bool {
	if m != nil {
		return m.Isaddon
	}
	return false
}

type StaffMember struct {
	B                    *ResponseBase `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Userid               string        `protobuf:"bytes,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Locationid           string        `protobuf:"bytes,3,opt,name=locationid,proto3" json:"locationid,omitempty"`
	Isactive             bool          `protobuf:"varint,4,opt,name=isactive,proto3" json:"isactive,omitempty"`
	Firstname            string        `protobuf:"bytes,5,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string        `protobuf:"bytes,6,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email                string        `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Mobile               string        `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Title                string        `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	Designation          string        `protobuf:"bytes,10,opt,name=designation,proto3" json:"designation,omitempty"`
	Issecondshift        bool          `protobuf:"varint,11,opt,name=issecondshift,proto3" json:"issecondshift,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StaffMember) Reset()         { *m = StaffMember{} }
func (m *StaffMember) String() string { return proto.CompactTextString(m) }
func (*StaffMember) ProtoMessage()    {}
func (*StaffMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8192a35440e287, []int{6}
}

func (m *StaffMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaffMember.Unmarshal(m, b)
}
func (m *StaffMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaffMember.Marshal(b, m, deterministic)
}
func (m *StaffMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaffMember.Merge(m, src)
}
func (m *StaffMember) XXX_Size() int {
	return xxx_messageInfo_StaffMember.Size(m)
}
func (m *StaffMember) XXX_DiscardUnknown() {
	xxx_messageInfo_StaffMember.DiscardUnknown(m)
}

var xxx_messageInfo_StaffMember proto.InternalMessageInfo

func (m *StaffMember) GetB() *ResponseBase {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *StaffMember) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *StaffMember) GetLocationid() string {
	if m != nil {
		return m.Locationid
	}
	return ""
}

func (m *StaffMember) GetIsactive() bool {
	if m != nil {
		return m.Isactive
	}
	return false
}

func (m *StaffMember) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *StaffMember) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *StaffMember) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *StaffMember) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *StaffMember) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *StaffMember) GetDesignation() string {
	if m != nil {
		return m.Designation
	}
	return ""
}

func (m *StaffMember) GetIssecondshift() bool {
	if m != nil {
		return m.Issecondshift
	}
	return false
}

type CategoryList struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CategoryList) Reset()         { *m = CategoryList{} }
func (m *CategoryList) String() string { return proto.CompactTextString(m) }
func (*CategoryList) ProtoMessage()    {}
func (*CategoryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8192a35440e287, []int{7}
}

func (m *CategoryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryList.Unmarshal(m, b)
}
func (m *CategoryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryList.Marshal(b, m, deterministic)
}
func (m *CategoryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryList.Merge(m, src)
}
func (m *CategoryList) XXX_Size() int {
	return xxx_messageInfo_CategoryList.Size(m)
}
func (m *CategoryList) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryList.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryList proto.InternalMessageInfo

func (m *CategoryList) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type CategoryDetailList struct {
	Categorydetails      []*CategoryDetail `protobuf:"bytes,2,rep,name=categorydetails,proto3" json:"categorydetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CategoryDetailList) Reset()         { *m = CategoryDetailList{} }
func (m *CategoryDetailList) String() string { return proto.CompactTextString(m) }
func (*CategoryDetailList) ProtoMessage()    {}
func (*CategoryDetailList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8192a35440e287, []int{8}
}

func (m *CategoryDetailList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryDetailList.Unmarshal(m, b)
}
func (m *CategoryDetailList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryDetailList.Marshal(b, m, deterministic)
}
func (m *CategoryDetailList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryDetailList.Merge(m, src)
}
func (m *CategoryDetailList) XXX_Size() int {
	return xxx_messageInfo_CategoryDetailList.Size(m)
}
func (m *CategoryDetailList) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryDetailList.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryDetailList proto.InternalMessageInfo

func (m *CategoryDetailList) GetCategorydetails() []*CategoryDetail {
	if m != nil {
		return m.Categorydetails
	}
	return nil
}

type FeatureList struct {
	Features             []*Feature `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FeatureList) Reset()         { *m = FeatureList{} }
func (m *FeatureList) String() string { return proto.CompactTextString(m) }
func (*FeatureList) ProtoMessage()    {}
func (*FeatureList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8192a35440e287, []int{9}
}

func (m *FeatureList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureList.Unmarshal(m, b)
}
func (m *FeatureList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureList.Marshal(b, m, deterministic)
}
func (m *FeatureList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureList.Merge(m, src)
}
func (m *FeatureList) XXX_Size() int {
	return xxx_messageInfo_FeatureList.Size(m)
}
func (m *FeatureList) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureList.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureList proto.InternalMessageInfo

func (m *FeatureList) GetFeatures() []*Feature {
	if m != nil {
		return m.Features
	}
	return nil
}

type StaffList struct {
	Members              []*StaffMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StaffList) Reset()         { *m = StaffList{} }
func (m *StaffList) String() string { return proto.CompactTextString(m) }
func (*StaffList) ProtoMessage()    {}
func (*StaffList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8192a35440e287, []int{10}
}

func (m *StaffList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaffList.Unmarshal(m, b)
}
func (m *StaffList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaffList.Marshal(b, m, deterministic)
}
func (m *StaffList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaffList.Merge(m, src)
}
func (m *StaffList) XXX_Size() int {
	return xxx_messageInfo_StaffList.Size(m)
}
func (m *StaffList) XXX_DiscardUnknown() {
	xxx_messageInfo_StaffList.DiscardUnknown(m)
}

var xxx_messageInfo_StaffList proto.InternalMessageInfo

func (m *StaffList) GetMembers() []*StaffMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*MeraResponse)(nil), "gservice.MeraResponse")
	proto.RegisterType((*Location)(nil), "gservice.Location")
	proto.RegisterType((*LocationList)(nil), "gservice.LocationList")
	proto.RegisterType((*Category)(nil), "gservice.Category")
	proto.RegisterType((*CategoryDetail)(nil), "gservice.CategoryDetail")
	proto.RegisterType((*Feature)(nil), "gservice.Feature")
	proto.RegisterType((*StaffMember)(nil), "gservice.StaffMember")
	proto.RegisterType((*CategoryList)(nil), "gservice.CategoryList")
	proto.RegisterType((*CategoryDetailList)(nil), "gservice.CategoryDetailList")
	proto.RegisterType((*FeatureList)(nil), "gservice.FeatureList")
	proto.RegisterType((*StaffList)(nil), "gservice.StaffList")
}

func init() { proto.RegisterFile("responses.proto", fileDescriptor_2f8192a35440e287) }

var fileDescriptor_2f8192a35440e287 = []byte{
	// 709 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcb, 0x6e, 0xdb, 0x3a,
	0x10, 0x85, 0xfc, 0x94, 0xc7, 0xce, 0xe3, 0x12, 0xb9, 0x01, 0x11, 0x5c, 0x5c, 0x18, 0x42, 0x16,
	0x69, 0x80, 0xba, 0xad, 0xbb, 0xe8, 0x26, 0x8b, 0x36, 0x2d, 0xda, 0x4d, 0xb2, 0x61, 0x37, 0x5d,
	0x96, 0x96, 0xc6, 0x0e, 0x01, 0x59, 0x32, 0x48, 0x3a, 0xa8, 0x3f, 0xa6, 0x1f, 0xd4, 0x45, 0xb7,
	0xfd, 0x9e, 0x42, 0x23, 0x51, 0xa6, 0xad, 0x20, 0x28, 0x50, 0x64, 0xa7, 0x39, 0x73, 0x66, 0xc8,
	0x19, 0xce, 0x1c, 0xc1, 0x91, 0x46, 0xb3, 0xca, 0x33, 0x83, 0x66, 0xb2, 0xd2, 0xb9, 0xcd, 0x59,
	0xb8, 0x30, 0xa8, 0xef, 0x55, 0x8c, 0x67, 0x43, 0x5c, 0xce, 0x30, 0x29, 0xe1, 0xe8, 0x12, 0x46,
	0xb7, 0xa8, 0xa5, 0xa8, 0xd8, 0xec, 0x0c, 0xc2, 0x85, 0x46, 0xb4, 0x2a, 0x5b, 0xf0, 0x60, 0x1c,
	0x5c, 0x0c, 0x44, 0x6d, 0x47, 0xdf, 0x3b, 0x10, 0xde, 0xe4, 0xb1, 0xb4, 0x2a, 0xcf, 0xd8, 0x39,
	0x04, 0x33, 0x62, 0x0c, 0xa7, 0xa7, 0x13, 0x97, 0x7b, 0xe2, 0xf2, 0x5c, 0x4b, 0x83, 0x22, 0x98,
	0x31, 0x06, 0x9d, 0x4c, 0x2e, 0x91, 0xb7, 0x28, 0x15, 0x7d, 0xb3, 0x31, 0x0c, 0x13, 0x65, 0x56,
	0xa9, 0xdc, 0x90, 0xab, 0x4d, 0x2e, 0x1f, 0x2a, 0x2e, 0xa1, 0x8c, 0x8c, 0xad, 0xba, 0x47, 0xde,
	0x19, 0x07, 0x17, 0xa1, 0xa8, 0x6d, 0xf6, 0x0c, 0x3a, 0x8b, 0x34, 0x8f, 0x79, 0x97, 0x8e, 0xfe,
	0x77, 0x7b, 0xf4, 0x27, 0xcc, 0xdd, 0xe5, 0x04, 0x51, 0xd8, 0x04, 0xc2, 0x34, 0x8f, 0x65, 0xaa,
	0xec, 0x86, 0xf7, 0x88, 0xce, 0xb6, 0xf4, 0x9b, 0xca, 0x23, 0x6a, 0x0e, 0x8b, 0x60, 0x24, 0x93,
	0x44, 0xa3, 0x31, 0xa9, 0xca, 0xf0, 0x15, 0xef, 0xd3, 0xcd, 0x76, 0xb0, 0x3d, 0xce, 0x94, 0x87,
	0x0d, 0xce, 0x94, 0x9d, 0x42, 0x6f, 0x99, 0xcf, 0x54, 0x8a, 0x7c, 0x40, 0xde, 0xca, 0x2a, 0x0a,
	0x5f, 0xdd, 0xe5, 0x19, 0x66, 0xeb, 0xe5, 0x0c, 0x35, 0x87, 0xb2, 0x70, 0x0f, 0x62, 0xc7, 0xd0,
	0x9e, 0xcb, 0x6f, 0x7c, 0x48, 0x9e, 0xe2, 0x93, 0xbd, 0x81, 0xa1, 0x4c, 0xd3, 0x39, 0x4a, 0xbb,
	0xd6, 0x68, 0xf8, 0x68, 0xbf, 0xea, 0x8f, 0xa5, 0xe7, 0x46, 0x19, 0x2b, 0x7c, 0x26, 0x7b, 0x07,
	0xc7, 0x69, 0xd5, 0x8e, 0x3a, 0xfa, 0xe0, 0xb1, 0xe8, 0x06, 0x9d, 0x4d, 0x80, 0xed, 0x61, 0x2a,
	0x31, 0xfc, 0x70, 0xdc, 0xbe, 0x18, 0x88, 0x07, 0x3c, 0xd1, 0x5b, 0x18, 0xb9, 0x17, 0x28, 0x32,
	0xb2, 0x97, 0x30, 0x70, 0x2c, 0xc3, 0x83, 0x71, 0xbb, 0xf9, 0x00, 0xf4, 0x58, 0x5b, 0x52, 0xf4,
	0x15, 0xc2, 0xf7, 0xd2, 0xe2, 0x22, 0xd7, 0x9b, 0xbf, 0x18, 0x30, 0x7f, 0x7c, 0xda, 0xbb, 0xe3,
	0x13, 0xfd, 0x0a, 0xe0, 0xd0, 0x1d, 0xf1, 0x01, 0xad, 0x54, 0xe9, 0xd3, 0x1c, 0xc4, 0xfe, 0x07,
	0x88, 0xab, 0x73, 0x54, 0x42, 0x53, 0x3c, 0x10, 0x1e, 0x52, 0x0c, 0x92, 0xb3, 0x28, 0x6f, 0xb7,
	0x1c, 0x24, 0x1f, 0x63, 0x97, 0x70, 0xbc, 0x92, 0x1a, 0x33, 0xeb, 0x65, 0xea, 0x11, 0xaf, 0x81,
	0x47, 0x3f, 0x5a, 0xd0, 0xaf, 0x9e, 0xf3, 0xe9, 0x2a, 0x72, 0x2f, 0xb5, 0xad, 0x68, 0x8b, 0x14,
	0x15, 0x39, 0xcb, 0xaf, 0xc8, 0xc7, 0x8a, 0x8a, 0xdc, 0x9d, 0x13, 0xea, 0xfe, 0xb6, 0xa2, 0x7d,
	0xbc, 0x18, 0xbf, 0x5d, 0x8c, 0xb2, 0x96, 0x4b, 0xf9, 0x80, 0x87, 0x71, 0xe8, 0xc7, 0x6b, 0xad,
	0xb3, 0x78, 0x53, 0x6d, 0xa5, 0x33, 0xd9, 0x09, 0x74, 0x57, 0x5a, 0xc5, 0xe5, 0x3e, 0x06, 0xa2,
	0x34, 0x0a, 0xbe, 0x32, 0x32, 0x49, 0xf2, 0x8c, 0x56, 0x31, 0x14, 0xce, 0x8c, 0x7e, 0xb6, 0x60,
	0xf8, 0xd9, 0xca, 0xf9, 0xfc, 0x16, 0x69, 0x2d, 0xff, 0xac, 0x9f, 0xa7, 0xd0, 0x5b, 0x1b, 0xd4,
	0x2a, 0xa9, 0x3a, 0x5a, 0x59, 0x7b, 0x7d, 0x6b, 0x37, 0xfa, 0xf6, 0x98, 0xda, 0xfd, 0x07, 0x83,
	0xb9, 0xd2, 0xc6, 0x7a, 0x0d, 0xdd, 0x02, 0x45, 0x64, 0x2a, 0x2b, 0x67, 0xd9, 0xc5, 0xda, 0x2e,
	0x6a, 0xc6, 0xa5, 0x54, 0x69, 0xd5, 0xb0, 0xd2, 0xf0, 0xa4, 0x29, 0xdc, 0x91, 0xa6, 0x13, 0xe8,
	0x5a, 0x65, 0x6b, 0xc5, 0x2a, 0x0d, 0x52, 0x6a, 0x34, 0x6a, 0x91, 0xd1, 0x55, 0x9d, 0x60, 0x79,
	0x10, 0x3b, 0x87, 0x03, 0x65, 0x0c, 0xc6, 0x79, 0x96, 0x98, 0x3b, 0x35, 0xb7, 0x24, 0x5d, 0xa1,
	0xd8, 0x05, 0xa3, 0x6b, 0x18, 0xb9, 0x9d, 0x23, 0x61, 0x98, 0xd6, 0xbb, 0xa1, 0xf0, 0x01, 0x65,
	0x70, 0x5c, 0xe1, 0xb1, 0xa2, 0x2f, 0xc0, 0x76, 0xf7, 0x96, 0x32, 0x5d, 0xc3, 0xd1, 0xee, 0x24,
	0x18, 0xde, 0xa2, 0x74, 0xbc, 0x99, 0xae, 0x0c, 0x13, 0xfb, 0x01, 0xd1, 0x15, 0x0c, 0x3d, 0x1d,
	0x64, 0xcf, 0x21, 0xac, 0x05, 0xb3, 0xbc, 0xda, 0x3f, 0x0d, 0xc1, 0x14, 0x35, 0x25, 0xba, 0x82,
	0x01, 0x8d, 0x0a, 0xc5, 0xbe, 0x80, 0xfe, 0x92, 0x46, 0xc6, 0x85, 0x7a, 0x5a, 0xeb, 0x0d, 0x94,
	0x70, 0xac, 0x59, 0x8f, 0xfe, 0xc2, 0xaf, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x9a, 0x40,
	0x7e, 0xaf, 0x07, 0x00, 0x00,
}
